{
 "title": "Meetup RSVPs Worldwide",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "panels": [
  {
   "title": "Meetup RSVPs Europe",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  mtime AS \"time\",\n  group_city,\n  group_lat,\n  group_lon,\n  count(event_id) AS \"event_cnt\"\nFROM rsvps_epoch\nWHERE\n  $__unixEpochFilter(mtime)\nGROUP BY mtime, group_city, group_lat, group_lon\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 0 },
   "content": "# Krakow Meetup 2019\n\nThe Panels in this Dashboard display a sample of charts with data from the PostgreSQL database populate in real-time from StreamSets.\n\n\n"
  },
  {
   "title": "Meetup RSVPs N. America",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  mtime AS \"time\",\n  group_city,\n  group_lat,\n  group_lon,\n  count(event_id) AS \"event_cnt\"\nFROM rsvps_epoch\nWHERE\n  $__unixEpochFilter(mtime)\nGROUP BY mtime, group_city, group_lat, group_lon\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Current RSVPs",
   "type": "singlestat",
   "description": "For selected Period",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(mtime,$__interval),\n  count(mtime) AS \"mtime\"\nFROM rsvps_epoch\nWHERE\n  $__unixEpochFilter(mtime)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "World Wide RSVPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(mtime,$__interval),\n  'Total RSVPs' AS metric,\n  count(event_id) AS \"events\"\nFROM rsvps_epoch\nWHERE\n  $__unixEpochFilter(mtime)\nGROUP BY 1,2\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(mtime,$__interval),\n  'RSVPd Yes' AS metric,\n  count(event_id) AS \"events\"\nFROM rsvps_epoch\nWHERE\n  $__unixEpochFilter(mtime) AND\n  response = 'yes'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}